name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  playwright-tests:
    strategy:
    # Re-order those to run remaining first and pre-pend the names for tests with multichain
      matrix:
        test-type: [remaining, multichain-testnet, multichain-local]
      max-parallel: 1
    defaults:
      run:
        working-directory: ./packages/near-fast-auth-signer-e2e-tests
    timeout-minutes: 60
    runs-on: ubuntu-22.04-4core
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18.x
    - name: Install dependencies
      run: |
        cd ${{ github.workspace }}/packages/near-fast-auth-signer-e2e-tests
        npm install -g yarn && yarn
    - name: Install Playwright Browsers
      run: yarn playwright install --with-deps
    - name: Run Playwright tests
      env:
        MAILTRAP_USER: ${{ secrets.MAILTRAP_USER }}
        MAILTRAP_PASS: ${{ secrets.MAILTRAP_PASS }}
        MAILTRAP_EMAIL: ${{ secrets.MAILTRAP_EMAIL }}
        FIREBASE_SERVICE_ACCOUNT_TESTNET: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TESTNET }}
        MULTICHAIN_TEST_ACCOUNT_ID: ${{ secrets.MULTICHAIN_TEST_ACCOUNT_ID }}
        MULTICHAIN_TEST_ACCOUNT_FAK: ${{ secrets.MULTICHAIN_TEST_ACCOUNT_FAK }}
        MULTICHAIN_TEST_ACCOUNT_LAK: ${{ secrets.MULTICHAIN_TEST_ACCOUNT_LAK }}
        MULTICHAIN_TEST_ACCOUNT_ID_2: ${{ secrets.MULTICHAIN_TEST_ACCOUNT_ID_2 }}
        MULTICHAIN_TEST_ACCOUNT_FAK_2: ${{ secrets.MULTICHAIN_TEST_ACCOUNT_FAK_2 }}
        MULTICHAIN_TEST_ACCOUNT_ID_3: ${{ secrets.MULTICHAIN_TEST_ACCOUNT_ID_3 }}
        MULTICHAIN_TEST_ACCOUNT_FAK_3: ${{ secrets.MULTICHAIN_TEST_ACCOUNT_FAK_3 }}
        ETH_PROVIDER_URL_TESTNET: ${{ secrets.ETH_PROVIDER_URL_TESTNET }}
        BNB_PROVIDER_URL_TESTNET: ${{ secrets.BNB_PROVIDER_URL_TESTNET }}
        BTC_PROVIDER_URL_TESTNET: ${{ secrets.BTC_PROVIDER_URL_TESTNET }}
      run: |
        if [ "${{ matrix.test-type }}" = "multichain-testnet" ]; then
          yarn test:multichain-testnet
        elif [ "${{ matrix.test-type }}" = "multichain-local" ]; then
          yarn test:multichain-local
        else
          yarn test:remaining
        fi
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-${{ matrix.test-type }}
        path: ./packages/near-fast-auth-signer-e2e-tests/playwright-report/
        retention-days: 30