name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    defaults:
      run:
        working-directory: ./packages/near-fast-auth-signer-e2e-tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm install -g yarn && yarn
    - name: Install Playwright Browsers
      run: yarn playwright install --with-deps
    - name: Checkout pagoda-relayer-rs repository
      uses: actions/checkout@v3
      with:
        repository: 'near/pagoda-relayer-rs'
        path: 'pagoda-relayer-rs'
    - name: Setup Rust environment
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
    - name: List directories
      run: ls -la ${{ github.workspace }}
    - name: Build and run pagoda-relayer-rs
      run: |
        ls
        cd ${{ github.workspace }}/pagoda-relayer-rs
        cargo build --release
        cargo run &
      shell: /usr/bin/bash -e {0}
    - name: Run Playwright tests
      env:
          MAILTRAP_USER: ${{ secrets.MAILTRAP_USER }}
          MAILTRAP_PASS: ${{ secrets.MAILTRAP_PASS }}
      run: yarn playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: ./packages/near-fast-auth-signer-e2e-tests/playwright-report/
        retention-days: 30