name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    defaults:
      run:
        working-directory: ./packages/near-fast-auth-signer-e2e-tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Checkout pagoda-relayer-rs repository
      uses: actions/checkout@v3
      with:
        repository: 'near/pagoda-relayer-rs'
        path: 'pagoda-relayer-rs'
    - name: Cache Rust dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    - name: Setup Rust environment
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
    - name: Build pagoda-relayer-rs
      run: |
        cd ${{ github.workspace }}/pagoda-relayer-rs
        cargo build --release
      shell: /usr/bin/bash -e {0}
    - name: Start server in the background
      run: |
        cd ${{ github.workspace }}/pagoda-relayer-rs
        cargo run &
        SERVER_PID=$!
    - name: Wait for server to be ready
      run: |
        echo "Waiting for server to start..."
        timeout=60 # timeout in seconds
        while ! curl --output /dev/null --silent --fail http://localhost:3030; do
          printf '.'
          sleep 5
          timeout=$((timeout-5))
          if [ "$timeout" -le 0 ]; then
            echo "Server did not start in time."
            exit 1
          fi
        done
        echo "Server is up and running!"
    - name: Start server and redirect output to a file
      run: |
        cargo run > server.log 2>&1 &
    - name: Install dependencies
      run: npm install -g yarn && yarn
    - name: Install Playwright Browsers
      run: yarn playwright install --with-deps
    - name: Run Playwright tests
      env:
          MAILTRAP_USER: ${{ secrets.MAILTRAP_USER }}
          MAILTRAP_PASS: ${{ secrets.MAILTRAP_PASS }}
      run: yarn playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: ./packages/near-fast-auth-signer-e2e-tests/playwright-report/
        retention-days: 30
    - name: Cleanup background process
      if: always()
      run: |
        kill $SERVER_PID || echo "Process already terminated."