name: Push to GCR GitHub Action

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    environment: mainnet
    steps:      
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY_JSON }}
      - uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        with:
          registry: gcr.io
          project_id: fast-auth-sdk
          image_name: frontend
          image_tag: latest